<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Vehiculo extends Model
{
   /**
         * The attributes that are mass assignable.
         *
         * @var array
         */
    protected $fillable = [ 'placa' ,
    'kilometraje' ,
    'fecha',
    'Conductor',
    'licencia' ,
    'observacionesLicencia',
    'SOAT',
    'observacionesSOAT',
    'tecnicoMecanica' ,
    'observacionesTecnicoMecanica' ,
    'seguroDanios'  ,
    'observacionesSeguroDanios',
    'direccionalDelantera',
    'observacionesDireccionalDelantera' ,
    'direccionaltrasera' ,
    'observacionesDireccionalTrasera' ,
    'lucesAltas' ,
    'observacionesLucesAltas' ,
    'lucesBajas' ,
    'observacionesLucesBajas' ,
    'lucesStop' ,
    'observacionesLucesStop',
    'lucesReversa'  ,
    'observacionesLucesReversa' ,
    'lucesParqueo' ,
    'observacionesLucesParqueo' ,
    'parabrisas' ,
    'observacionesParabrisas' ,
    'frenosPrincipal',
    'observacionesFrenosPrincipal',
    'frenosEmergencia',
    'observacionesFrenosEmergencia',
    'llantasDelateras' ,
    'observacionesLlantasDelanteras',
    'llantasTraseras' ,
    'observacionesLlantasTraseras' ,
    'llantasRepuesto' ,
    'observacionesLlantasRepuesto' ,
    'espejosLaterales' ,
    'observacionesEspejosLaterales' ,
    'EspejoRetrovisor',
    'observacionesEspejoRetrovisor',
    'RespuestaPito' ,
    'observacionesRespuestaPito' ,
    'frenos' ,
    'observacionesFrenos' ,
    'aceite' ,
    'observacionesAceite',
    'refiregante' ,
    'observacionesRefigerante',
    'apoyoDelantero' ,
    'observacionesApoyoDelantero' ,
    'apoyoTrasero' ,
    'observacionesApoyoTrasero',
    'cinturonesDelanteros' ,
    'observacionesCinturonesDelantero' ,
    'cinturonesTraseros' ,
    'observacionesCinturonesTraseros' ,
    'cambioAceite' ,
    'observacionesCambioAceite' ,
    'sincronizacion' ,
    'observacionesSincronizacion' ,
    'alineacionBalanceo' ,
    'observacionesAlineacionBalanceo' ,
    'cambiosLlantas' ,
    'observacionesCambioLlantas' ,
    'tecnomecanicaVencimiento' ,
    'observacionesTecnomecanicaVencimiento' ,
    'soatVencimiento'  ,
    'observacionesSoatVencimiento' ,
    'observacionesElementos' ,
    'extintor',
    'fechaVencimientoExtintor',
    'capacidadExtintor',
    'observacionesExtintor',
    'herramientas'  ,
    'cruzeta'  ,
    'observacionesHerramientasCruceta' ,
    'gato' ,
    'tacos'  ,
    'observacionesGatoTacos' ,
    'senales'  ,
    'chaleco'  ,
    'observacionesSenalesChaleco',
    'botiquin' ,
    'observacionesBotiquin',
    'observacionesGenerales',
    'NombreCompleto',
    'Cedula',
    'Objetivo',
    'Destino',
    'FechaDelServicio',
    'NombreJefe'
    
];

protected $dates = [
    'fecha'
];
}
